// Multi-language translation system
const translations = {
  ar: {
    title: "وكالتك الاستثمارية",
    logo: "CASHALOW AGENCY",
    pricing: "الأسعار",
    license: "تفعيل الترخيص",
    buyCoins: "شراء العملات",
    contact: "اتصل بنا",
    getStarted: "الباقات",
    home: "الرئيسية",
    contactBtn: "اتصل بنا",
    pkg1Title: "إحتراف التداول",
    pkg1Desc: "هل أنت مبتدئ في عالم التداول ولا تعرف من أين تبدأ؟<br>هذه الدورة المجانية صنعت خصيصًا لك!<br>تعلم الأساسيات بخطوات بسيطة وبأسلوب ممتع وسهل.<br>ستحصل على معلومات قيّمة لم تسمع بها من قبل.<br>بداية رحلتك نحو الربح تبدأ من هنا، مجانًا!<br>لا تضيع الفرصة، مستقبلك الاستثماري يبدأ الآن.",
    pkg1Btn: "ابدأ الآن",
    pkg2Title: "كتابك حياتك",
    pkg2Desc: "نقدم لك أعظم كتاب في حياتك، مجانًا!<br>هذا الكتاب لا تقرأه فقط، بل تعيشه وتبدأ تطبيقه.<br>فيه خلاصة تجارب وأفكار تغيّر عقلك وطريقتك في التفكير.<br>مفاتيح النجاح والحرية المالية بين يديك الآن.<br>استثمر وقتك في المعرفة، وابدأ التغيير.<br>لأن النجاح يبدأ من العقل، اقرأ لتنهض!",
    pkg2Btn: "احصل عليه",
    pkg3Title: "التجارة الإلكترونية",
    pkg3Desc: "تعلّم كيف تنشئ متجرك وتبيع منتجاتك حول العالم.<br>نكشف لك أسرار الشحن والتسويق والتحويلات الناجحة.<br>طرق حديثة للربح من الإنترنت بسهولة وذكاء.<br>محتوى عملي واحترافي من رواد التجارة الإلكترونية.<br>كل ما تحتاجه للنجاح متوفر داخل هذه الباقة.<br>انطلق اليوم نحو مشروعك الأول بثقة!",
    pkg3Btn: "تعلم الآن",
    pkg4Title: "التجارة الرقمية",
    pkg4Desc: "استثمر في أقوى المجالات بالعالم الرقمي.<br>تعلم كيف تنشئ مصادر دخل رقمية دائمة.<br>نصائح من محترفين ومجربين في هذا المجال.<br>بيع منتجات رقمية، خدمات، أو دورات بسهولة.<br>أنت فقط بحاجة للإنترنت وعقل مفتوح للربح.<br>اجعل العالم الرقمي مصدر دخلك الحقيقي.",
    pkg4Btn: "ابدأ"
  },
  tr: {
    title: "Cashflow Ajansı",
    logo: "CASHALOW AGENCY",
    pricing: "Fiyatlandırma",
    license: "Lisans Aktivasyonu",
    buyCoins: "Coin Satın Al",
    contact: "İletişim",
    getStarted: "Paketler",
    home: "Ana Sayfa",
    contactBtn: "İletişim",
    pkg1Title: "Ticaret Ustalığı",
    pkg1Desc: "Yatırıma yeni mi başlıyorsunuz ve nereden başlayacağınızı bilmiyor musunuz?<br>Bu ücretsiz kurs tam size göre!<br>Temelleri basit adımlarla ve eğlenceli bir şekilde öğrenin.<br>Daha önce duymadığınız değerli bilgiler edinin.<br>Kazanç yolculuğunuz burada başlıyor, ücretsiz!<br>Fırsatı kaçırmayın, yatırım geleceğiniz şimdi başlıyor.",
    pkg1Btn: "Hemen Başla",
    pkg2Title: "Hayat Kitabınız",
    pkg2Desc: "Hayatınızdaki en büyük kitabı size ücretsiz sunuyoruz!<br>Bu kitap sadece okumak için değil, yaşamak ve uygulamak içindir.<br>Zihninizi ve düşünce tarzınızı değiştiren deneyimlerin ve fikirlerin özünü içerir.<br>Başarı ve finansal özgürlüğün anahtarları artık elinizde.<br>Zamanınızı bilgiye yatırın ve değişime başlayın.<br>Başarı zihinden başlar, yükselmek için okuyun!",
    pkg2Btn: "Al",
    pkg3Title: "E-Ticaret",
    pkg3Desc: "Mağazanızı nasıl oluşturacağınızı ve ürünlerinizi dünya çapında nasıl satacağınızı öğrenin.<br>Kargo, pazarlama ve başarılı dönüşümlerin sırlarını açıklıyoruz.<br>Kolay ve akıllı bir şekilde çevrimiçi para kazanmanın modern yolları.<br>E-ticaret öncülerinden pratik ve profesyonel içerik.<br>Başarı için ihtiyacınız olan her şey bu pakette mevcut.<br>İlk projenize bugün güvenle başlayın!",
    pkg3Btn: "Şimdi Öğren",
    pkg4Title: "Dijital İş",
    pkg4Desc: "Dijital dünyadaki en güçlü alanlara yatırım yapın.<br>Kalıcı dijital gelir kaynakları oluşturmayı öğrenin.<br>Bu alanda profesyonellerden ve deneyimlilerden ipuçları.<br>Dijital ürünleri, hizmetleri veya kursları kolayca satın.<br>Kazanç için sadece internete ve açık bir zihne ihtiyacınız var.<br>Dijital dünyayı gerçek gelir kaynağınız yapın.",
    pkg4Btn: "Başla"
  },
  en: {
    title: "Cashflow Agency",
    logo: "CASHALOW AGENCY",
    pricing: "Pricing",
    license: "License Activation",
    buyCoins: "Buy Coins",
    contact: "Contact Us",
    getStarted: "Packages",
    home: "Home",
    contactBtn: "Contact Us",
    pkg1Title: "Trading Mastery",
    pkg1Desc: "Are you a beginner in trading and don't know where to start?<br>This free course is made just for you!<br>Learn the basics in simple steps and an enjoyable style.<br>You will get valuable information you've never heard before.<br>Your journey to profit starts here, for free!<br>Don't miss the opportunity, your investment future starts now.",
    pkg1Btn: "Start Now",
    pkg2Title: "Your Life Book",
    pkg2Desc: "We offer you the greatest book in your life, for free!<br>This book is not just for reading, but for living and applying.<br>It contains the essence of experiences and ideas that change your mind and way of thinking.<br>The keys to success and financial freedom are now in your hands.<br>Invest your time in knowledge and start changing.<br>Success starts from the mind, read to rise!",
    pkg2Btn: "Get it",
    pkg3Title: "E-Commerce",
    pkg3Desc: "Learn how to create your store and sell your products worldwide.<br>We reveal to you the secrets of shipping, marketing, and successful conversions.<br>Modern ways to earn online easily and smartly.<br>Practical and professional content from e-commerce pioneers.<br>Everything you need for success is available in this package.<br>Start your first project with confidence today!",
    pkg3Btn: "Learn Now",
    pkg4Title: "Digital Business",
    pkg4Desc: "Invest in the strongest fields in the digital world.<br>Learn how to create permanent digital income sources.<br>Tips from professionals and experienced people in this field.<br>Sell digital products, services, or courses easily.<br>You only need the internet and an open mind to profit.<br>Make the digital world your real income source.",
    pkg4Btn: "Start"
  },
  hi: {
    title: "कैशफ्लो एजेंसी",
    logo: "CASHALOW AGENCY",
    pricing: "मूल्य निर्धारण",
    license: "लाइसेंस सक्रियण",
    buyCoins: "सिक्के खरीदें",
    contact: "संपर्क करें",
    getStarted: "पैकेज",
    home: "होम",
    contactBtn: "संपर्क करें",
    pkg1Title: "ट्रेडिंग मास्टरी",
    pkg1Desc: "क्या आप ट्रेडिंग में नए हैं और नहीं जानते कि कहां से शुरू करें?<br>यह मुफ्त कोर्स आपके लिए है!<br>सरल चरणों में और मज़ेदार तरीके से मूल बातें सीखें।<br>आपको ऐसी मूल्यवान जानकारी मिलेगी जो आपने पहले कभी नहीं सुनी होगी।<br>आपकी कमाई की यात्रा यहाँ से शुरू होती है, मुफ्त में!<br>मौका न चूकें, आपका निवेश भविष्य अब शुरू होता है।",
    pkg1Btn: "अभी शुरू करें",
    pkg2Title: "आपकी जीवन पुस्तक",
    pkg2Desc: "हम आपको आपके जीवन की सबसे बड़ी पुस्तक मुफ्त में देते हैं!<br>यह पुस्तक केवल पढ़ने के लिए नहीं, बल्कि जीने और लागू करने के लिए है।<br>यह अनुभवों और विचारों का सार रखती है जो आपके दिमाग और सोचने के तरीके को बदल देती है।<br>सफलता और वित्तीय स्वतंत्रता की कुंजी अब आपके हाथ में है।<br>अपने समय का निवेश ज्ञान में करें और बदलाव शुरू करें।<br>सफलता दिमाग से शुरू होती है, उठने के लिए पढ़ें!",
    pkg2Btn: "प्राप्त करें",
    pkg3Title: "ई-कॉमर्स",
    pkg3Desc: "जानें कि अपनी दुकान कैसे बनाएं और अपने उत्पादों को दुनिया भर में कैसे बेचें।<br>हम आपको शिपिंग, मार्केटिंग और सफल रूपांतरणों के रहस्य बताते हैं।<br>ऑनलाइन कमाई के आधुनिक तरीके, आसानी से और स्मार्ट तरीके से।<br>ई-कॉमर्स अग्रदूतों से व्यावहारिक और पेशेवर सामग्री।<br>सफलता के लिए आपको जो कुछ भी चाहिए वह इस पैकेज में उपलब्ध है।<br>आज ही आत्मविश्वास के साथ अपना पहला प्रोजेक्ट शुरू करें!",
    pkg3Btn: "अब जानें",
    pkg4Title: "डिजिटल बिजनेस",
    pkg4Desc: "डिजिटल दुनिया के सबसे मजबूत क्षेत्रों में निवेश करें।<br>स्थायी डिजिटल आय स्रोत बनाना सीखें।<br>इस क्षेत्र में पेशेवरों और अनुभवी लोगों से टिप्स।<br>डिजिटल उत्पाद, सेवाएं या कोर्स आसानी से बेचें।<br>कमाई के लिए आपको केवल इंटरनेट और खुले दिमाग की आवश्यकता है।<br>डिजिटल दुनिया को अपनी असली आय का स्रोत बनाएं।",
    pkg4Btn: "शुरू करें"
  },
  fr: {
  es: {
    title: "Agencia Cashflow",
    logo: "CASHALOW AGENCY",
    pricing: "Precios",
    license: "Activación de licencia",
    buyCoins: "Comprar monedas",
    contact: "Contáctenos",
    getStarted: "Paquetes",
    home: "Inicio",
    contactBtn: "Contáctenos",
    pkg1Title: "Maestría en trading",
    pkg1Desc: "¿Eres principiante en el trading y no sabes por dónde empezar?<br>¡Este curso gratuito es para ti!<br>Aprende lo básico en pasos simples y de forma divertida.<br>Obtendrás información valiosa que nunca antes habías escuchado.<br>¡Tu viaje hacia las ganancias comienza aquí, gratis!<br>No pierdas la oportunidad, tu futuro de inversión comienza ahora.",
    pkg1Btn: "Comenzar",
    pkg2Title: "El libro de tu vida",
    pkg2Desc: "¡Te ofrecemos el libro más grande de tu vida, gratis!<br>Este libro no es solo para leer, sino para vivir y aplicar.<br>Contiene la esencia de experiencias e ideas que cambian tu mente y tu forma de pensar.<br>Las claves del éxito y la libertad financiera ahora están en tus manos.<br>Invierte tu tiempo en conocimiento y comienza a cambiar.<br>¡El éxito comienza en la mente, lee para elevarte!",
    pkg2Btn: "Obtener",
    pkg3Title: "Comercio electrónico",
    pkg3Desc: "Aprende cómo crear tu tienda y vender tus productos en todo el mundo.<br>Te revelamos los secretos del envío, el marketing y las conversiones exitosas.<br>Formas modernas de ganar dinero en línea fácil e inteligentemente.<br>Contenido práctico y profesional de pioneros del comercio electrónico.<br>Todo lo que necesitas para el éxito está disponible en este paquete.<br>¡Comienza tu primer proyecto con confianza hoy!",
    pkg3Btn: "Aprender",
    pkg4Title: "Negocio digital",
    pkg4Desc: "Invierte en los campos más fuertes del mundo digital.<br>Aprende cómo crear fuentes de ingresos digitales permanentes.<br>Consejos de profesionales y personas experimentadas en este campo.<br>Vende productos digitales, servicios o cursos fácilmente.<br>Solo necesitas internet y una mente abierta para ganar dinero.<br>Haz del mundo digital tu verdadera fuente de ingresos.",
    pkg4Btn: "Comenzar"
  },
  de: {
    title: "Cashflow-Agentur",
    logo: "CASHALOW AGENCY",
    pricing: "Preise",
    license: "Lizenzaktivierung",
    buyCoins: "Münzen kaufen",
    contact: "Kontakt",
    getStarted: "Pakete",
    home: "Startseite",
    contactBtn: "Kontakt",
    pkg1Title: "Trading-Meisterschaft",
    pkg1Desc: "Sind Sie Anfänger im Trading und wissen nicht, wo Sie anfangen sollen?<br>Dieser kostenlose Kurs ist genau das Richtige für Sie!<br>Lernen Sie die Grundlagen in einfachen Schritten und auf unterhaltsame Weise.<br>Sie erhalten wertvolle Informationen, die Sie noch nie zuvor gehört haben.<br>Ihre Reise zum Gewinn beginnt hier, kostenlos!<br>Verpassen Sie nicht die Gelegenheit, Ihre Investitionszukunft beginnt jetzt.",
    pkg1Btn: "Starten",
    pkg2Title: "Ihr Lebensbuch",
    pkg2Desc: "Wir bieten Ihnen das größte Buch Ihres Lebens kostenlos an!<br>Dieses Buch ist nicht nur zum Lesen, sondern zum Leben und Anwenden.<br>Es enthält die Essenz von Erfahrungen und Ideen, die Ihren Geist und Ihre Denkweise verändern.<br>Die Schlüssel zum Erfolg und zur finanziellen Freiheit liegen jetzt in Ihren Händen.<br>Investieren Sie Ihre Zeit in Wissen und beginnen Sie mit der Veränderung.<br>Der Erfolg beginnt im Kopf, lesen Sie, um aufzusteigen!",
    pkg2Btn: "Erhalten",
    pkg3Title: "E-Commerce",
    pkg3Desc: "Erfahren Sie, wie Sie Ihren Shop erstellen und Ihre Produkte weltweit verkaufen.<br>Wir verraten Ihnen die Geheimnisse des Versands, Marketings und erfolgreicher Conversions.<br>Moderne Möglichkeiten, online einfach und intelligent Geld zu verdienen.<br>Praktische und professionelle Inhalte von E-Commerce-Pionieren.<br>Alles, was Sie für den Erfolg brauchen, ist in diesem Paket verfügbar.<br>Starten Sie Ihr erstes Projekt noch heute mit Zuversicht!",
    pkg3Btn: "Lernen",
    pkg4Title: "Digitales Geschäft",
    pkg4Desc: "Investieren Sie in die stärksten Bereiche der digitalen Welt.<br>Lernen Sie, wie Sie dauerhafte digitale Einkommensquellen schaffen.<br>Tipps von Profis und erfahrenen Leuten in diesem Bereich.<br>Verkaufen Sie digitale Produkte, Dienstleistungen oder Kurse einfach.<br>Sie brauchen nur das Internet und einen offenen Geist, um Geld zu verdienen.<br>Machen Sie die digitale Welt zu Ihrer echten Einkommensquelle.",
    pkg4Btn: "Starten"
  },
  zh: {
    title: "现金流代理",
    logo: "CASHALOW AGENCY",
    pricing: "价格",
    license: "许可证激活",
    buyCoins: "购买硬币",
    contact: "联系我们",
    getStarted: "套餐",
    home: "首页",
    contactBtn: "联系我们",
    pkg1Title: "交易精通",
    pkg1Desc: "您是交易新手，不知道从哪里开始吗？<br>本免费课程专为您打造！<br>以简单的步骤和有趣的方式学习基础知识。<br>您将获得前所未有的宝贵信息。<br>您的盈利之旅从这里开始，免费！<br>不要错过机会，您的投资未来现在开始。",
    pkg1Btn: "立即开始",
    pkg2Title: "你的人生之书",
    pkg2Desc: "我们为您免费提供人生中最伟大的书！<br>这本书不仅仅是用来阅读，更是用来生活和实践的。<br>它包含了改变您思维和思考方式的经验和想法的精华。<br>成功和财务自由的钥匙现在就在您手中。<br>把时间投资在知识上，开始改变。<br>成功始于思想，阅读让你提升！",
    pkg2Btn: "获取",
    pkg3Title: "电子商务",
    pkg3Desc: "学习如何创建您的商店并在全球范围内销售您的产品。<br>我们为您揭示运输、营销和成功转化的秘诀。<br>轻松智能地在线赚钱的现代方法。<br>来自电子商务先驱的实用和专业内容。<br>成功所需的一切都在此套餐中。<br>立即自信地开始您的第一个项目！",
    pkg3Btn: "学习",
    pkg4Title: "数字业务",
    pkg4Desc: "投资于数字世界中最强大的领域。<br>学习如何创建永久的数字收入来源。<br>来自该领域专业人士和有经验者的建议。<br>轻松销售数字产品、服务或课程。<br>您只需要互联网和开放的思维即可获利。<br>让数字世界成为您的真正收入来源。",
    pkg4Btn: "开始"
  },
  ur: {
    title: "کیش فلو ایجنسی",
    logo: "CASHALOW AGENCY",
    pricing: "قیمتیں",
    license: "لائسنس کی فعالیت",
    buyCoins: "سکے خریدیں",
    contact: "رابطہ کریں",
    getStarted: "پیکجز",
    home: "ہوم",
    contactBtn: "رابطہ کریں",
    pkg1Title: "ٹریڈنگ مہارت",
    pkg1Desc: "کیا آپ ٹریڈنگ میں نئے ہیں اور نہیں جانتے کہاں سے شروع کریں؟<br>یہ مفت کورس آپ کے لیے ہے!<br>آسان مراحل میں اور دلچسپ انداز میں بنیادی باتیں سیکھیں۔<br>آپ کو ایسی قیمتی معلومات ملیں گی جو آپ نے پہلے کبھی نہیں سنیں۔<br>آپ کا منافع کا سفر یہاں سے شروع ہوتا ہے، مفت میں!<br>موقع ضائع نہ کریں، آپ کا سرمایہ کاری مستقبل اب شروع ہوتا ہے۔",
    pkg1Btn: "اب شروع کریں",
    pkg2Title: "آپ کی زندگی کی کتاب",
    pkg2Desc: "ہم آپ کو آپ کی زندگی کی سب سے بڑی کتاب مفت دیتے ہیں!<br>یہ کتاب صرف پڑھنے کے لیے نہیں، بلکہ جینے اور لاگو کرنے کے لیے ہے۔<br>یہ تجربات اور خیالات کا نچوڑ رکھتی ہے جو آپ کے دماغ اور سوچنے کے انداز کو بدل دیتی ہے۔<br>کامیابی اور مالی آزادی کی چابیاں اب آپ کے ہاتھ میں ہیں۔<br>اپنا وقت علم میں لگائیں اور تبدیلی شروع کریں۔<br>کامیابی دماغ سے شروع ہوتی ہے، اٹھنے کے لیے پڑھیں!",
    pkg2Btn: "حاصل کریں",
    pkg3Title: "ای کامرس",
    pkg3Desc: "سیکھیں کہ اپنی دکان کیسے بنائیں اور اپنی مصنوعات دنیا بھر میں کیسے فروخت کریں۔<br>ہم آپ کو شپنگ، مارکیٹنگ اور کامیاب تبدیلیوں کے راز بتاتے ہیں۔<br>آن لائن کمائی کے جدید طریقے، آسانی سے اور ذہانت سے۔<br>ای کامرس کے پیش روؤں سے عملی اور پیشہ ورانہ مواد۔<br>کامیابی کے لیے آپ کو جو کچھ بھی چاہیے وہ اس پیکج میں دستیاب ہے۔<br>آج ہی اعتماد کے ساتھ اپنا پہلا پروجیکٹ شروع کریں!",
    pkg3Btn: "اب سیکھیں",
    pkg4Title: "ڈیجیٹل بزنس",
    pkg4Desc: "ڈیجیٹل دنیا کے سب سے مضبوط شعبوں میں سرمایہ کاری کریں۔<br>مستقل ڈیجیٹل آمدنی کے ذرائع بنانا سیکھیں۔<br>اس شعبے میں پیشہ ور افراد اور تجربہ کار لوگوں سے نکات۔<br>ڈیجیٹل مصنوعات، خدمات یا کورسز آسانی سے فروخت کریں۔<br>کمائی کے لیے آپ کو صرف انٹرنیٹ اور کھلے ذہن کی ضرورت ہے۔<br>ڈیجیٹل دنیا کو اپنی حقیقی آمدنی کا ذریعہ بنائیں۔",
    pkg4Btn: "شروع کریں"
  },
    title: "Agence Cashflow",
    logo: "CASHALOW AGENCY",
    pricing: "Tarifs",
    license: "Activation de licence",
    buyCoins: "Acheter des pièces",
    contact: "Contactez-nous",
    getStarted: "Forfaits",
    home: "Accueil",
    contactBtn: "Contactez-nous",
    pkg1Title: "Maîtrise du trading",
    pkg1Desc: "Vous débutez dans le trading et ne savez pas par où commencer ?<br>Ce cours gratuit est fait pour vous !<br>Apprenez les bases en étapes simples et de manière ludique.<br>Vous obtiendrez des informations précieuses jamais entendues auparavant.<br>Votre parcours vers le profit commence ici, gratuitement !<br>Ne ratez pas l'opportunité, votre avenir d'investisseur commence maintenant.",
    pkg1Btn: "Commencer",
    pkg2Title: "Le livre de votre vie",
    pkg2Desc: "Nous vous offrons le plus grand livre de votre vie, gratuitement !<br>Ce livre n'est pas seulement à lire, mais à vivre et à appliquer.<br>Il contient l'essence d'expériences et d'idées qui changent votre esprit et votre façon de penser.<br>Les clés du succès et de la liberté financière sont maintenant entre vos mains.<br>Investissez votre temps dans la connaissance et commencez à changer.<br>Le succès commence dans l'esprit, lisez pour vous élever !",
    pkg2Btn: "L'obtenir",
    pkg3Title: "E-Commerce",
    pkg3Desc: "Apprenez à créer votre boutique et à vendre vos produits dans le monde entier.<br>Nous vous révélons les secrets de l'expédition, du marketing et des conversions réussies.<br>Des moyens modernes de gagner de l'argent en ligne facilement et intelligemment.<br>Contenu pratique et professionnel des pionniers du e-commerce.<br>Tout ce dont vous avez besoin pour réussir est disponible dans ce forfait.<br>Lancez votre premier projet avec confiance dès aujourd'hui !",
    pkg3Btn: "Apprendre",
    pkg4Title: "Business digital",
    pkg4Desc: "Investissez dans les domaines les plus puissants du monde numérique.<br>Apprenez à créer des sources de revenus numériques permanentes.<br>Des conseils de professionnels et d'experts dans ce domaine.<br>Vendez des produits numériques, des services ou des cours facilement.<br>Vous n'avez besoin que d'internet et d'un esprit ouvert pour gagner de l'argent.<br>Faites du monde numérique votre véritable source de revenus.",
    pkg4Btn: "Commencer"
  }
};

function setLanguage(lang) {
  if (!translations[lang]) return;
  document.documentElement.lang = lang;
  document.querySelectorAll('[data-translate]').forEach(el => {
    const key = el.getAttribute('data-translate');
    if (translations[lang][key]) {
      if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
        el.placeholder = translations[lang][key];
      } else {
        el.innerHTML = translations[lang][key];
      }
    }
  });
}

// Auto-detect or default
const savedLang = localStorage.getItem('lang') || 'ar';
setLanguage(savedLang);

// لا تكرر منطق أزرار اللغة هنا. الكود موجود في navbar.js لضمان عمله في كل الصفحات.

